<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "qc_info_rights"
 *
 * Auto generated by Extension Builder 2021-09-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'qc_references',
    'description' => "Module sert à afficher les références d'une page sélectionnée.",
    'category' => 'Module',
    'state' => 'beta',
    'version' => '1.0.0',
    'autoload' => [
        'psr-4' => [
            'Qc\\QcReferences\\' => 'Classes',
        ],
    ],
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
