services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Qc\QcReferences\:
    resource: '../Classes/*'

  Qc\QcReferences\Domain\Repository\ReferenceRepository:
    public: true




